const GAME_CONFIG = {
  SERVER_URL: 'http://localhost:3000',
  EGG_TYPES: [
    { name: 'Starter', cost: 100, emoji: '🥚', color: '#FFF8DC' },
    { name: 'Forest', cost: 250, emoji: '🌿', color: '#90EE90' },
    { name: 'Ocean', cost: 500, emoji: '🌊', color: '#87CEEB' },
    { name: 'Crystal', cost: 1000, emoji: '💎', color: '#E6E6FA' },
    { name: 'Void', cost: 2000, emoji: '🌑', color: '#2F4F4F' },
    { name: 'Celestial', cost: 5000, emoji: '⭐', color: '#4B0082' },
  ],
  RARITIES: [
    { name: 'Common', chance: 0.1, emoji: '⚪' },
    { name: 'Uncommon', chance: 0.15, emoji: '🟢' },
    { name: 'Rare', chance: 0.2, emoji: '🔵' },
    { name: 'Elite', chance: 0.15, emoji: '🟣' },
    { name: 'Epic', chance: 0.12, emoji: '🟡' },
    { name: 'Legendary', chance: 0.1, emoji: '🔴' },
    { name: 'Mythic', chance: 0.07, emoji: '🩷' },
    { name: 'Ancient', chance: 0.05, emoji: '🔷' },
    { name: 'Divine', chance: 0.03, emoji: '💫' },
    { name: 'Secret', chance: 0.02, emoji: '🕷️' },
    { name: 'Transcendent', chance: 0.008, emoji: '✨' },
    { name: 'Impossible', chance: 0.002, emoji: '🌈' },
  ],
  MUTATIONS: [
    { name: 'None', emoji: '' },
    { name: 'Golden', emoji: '✨' },
    { name: 'Rainbow', emoji: '🌈' },
    { name: 'Shadow', emoji: '🌑' },
    { name: 'Corrupted', emoji: '☠️' },
    { name: 'Galactic', emoji: '🌌' },
  ],
  SPECIES: [
    { name: 'Dragon', emoji: '🐉' },
    { name: 'Phoenix', emoji: '🔥' },
    { name: 'Unicorn', emoji: '🦄' },
    { name: 'Fairy', emoji: '🧚' },
    { name: 'Griffin', emoji: '🦅' },
    { name: 'Kraken', emoji: '🐙' },
  ],
  FOOD: [
    { name: 'Apple', cost: 10, hunger: 20 },
    { name: 'Bread', cost: 20, hunger: 30 },
    { name: 'Fish', cost: 30, hunger: 25 },
    { name: 'Cake', cost: 50, hunger: 50 },
    { name: 'Golden Treat', cost: 100, hunger: 60 },
    { name: 'Cosmic Snack', cost: 250, hunger: 75 },
    { name: 'Divine Fruit', cost: 500, hunger: 100 },
  ],
};
